-- GoldenAge_Config
-- Author: HSbF6HSO3F
-- DateCreated: 2025/8/22 7:48:11
--------------------------------------------------------------
INSERT INTO PlayerItems
    (Domain,                        CivilizationType,           LeaderType,             Type,                                               Icon,                           Name,                                                       Description,                                                      SortIndex)
VALUES
    ('Players:Expansion2_Players',  'CIVILIZATION_IRON_BLOOD',  'LEADER_DEUTSCHLAND_A', 'GOLDEN_CIVILIZATION_IRON_BLOOD_CUSTOM_FEATURES',   'ICON_CIVILIZATION_IRON_BLOOD', 'LOC_GOLDEN_CIVILIZATION_IRON_BLOOD_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_IRON_BLOOD_CUSTOM_FEATURES_DESCRIPTION',  999),
    ('Players:Expansion2_Players',  'CIVILIZATION_IRON_BLOOD',  'LEADER_SEYDLITZ',      'GOLDEN_CIVILIZATION_IRON_BLOOD_CUSTOM_FEATURES',   'ICON_CIVILIZATION_IRON_BLOOD', 'LOC_GOLDEN_CIVILIZATION_IRON_BLOOD_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_IRON_BLOOD_CUSTOM_FEATURES_DESCRIPTION',  999),
    ('Players:Expansion2_Players',  'CIVILIZATION_IRON_BLOOD',  'LEADER_U_96_VIIC',     'GOLDEN_CIVILIZATION_IRON_BLOOD_CUSTOM_FEATURES',   'ICON_CIVILIZATION_IRON_BLOOD', 'LOC_GOLDEN_CIVILIZATION_IRON_BLOOD_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_IRON_BLOOD_CUSTOM_FEATURES_DESCRIPTION',  999),
    ('Players:Expansion2_Players',  'CIVILIZATION_IRON_BLOOD',  'LEADER_Z23_1936A',     'GOLDEN_CIVILIZATION_IRON_BLOOD_CUSTOM_FEATURES',   'ICON_CIVILIZATION_IRON_BLOOD', 'LOC_GOLDEN_CIVILIZATION_IRON_BLOOD_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_IRON_BLOOD_CUSTOM_FEATURES_DESCRIPTION',  999),
    ('Players:Expansion2_Players',  'CIVILIZATION_IRON_BLOOD',  'LEADER_Z46_1936C',     'GOLDEN_CIVILIZATION_IRON_BLOOD_CUSTOM_FEATURES',   'ICON_CIVILIZATION_IRON_BLOOD', 'LOC_GOLDEN_CIVILIZATION_IRON_BLOOD_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_IRON_BLOOD_CUSTOM_FEATURES_DESCRIPTION',  999);